version: '3'
services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGO_URL: ${MONGO_URL} # PONEMOS LA URL DE LA BASE DE DATOS EN MONGODB DE .ENV
      PORT: ${PORT} # PONEMOS EL PORT DE .ENV
      DEFAULT_LIMIT: ${DEFAULT_LIMIT} # PONEMOS EL DEFAULT DE .ENV
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-poke-api
    volumes:
      - ./mongo:/data/db